const tables = [
    {
        id:"Customer",
        attr:[
            {
                id:0,
                val:"cust_id"
            },
            {
                id:1,
                val:"cust_fname"
            },
            {
                id:2,
                val:"cust_lname"
            },
            {
                id:3,
                val:"cust_DOB"
            },
            {
                id:4,
                val:"cust_gender"
            },
            {
                id:5,
                val:"cust_address"
            },
            {
                id:6,
                val:"cust_mob_number"
            },
            {
                id:7,
                val:"cust_email"
            },
            {
                id:8,
                val:"cust_passport_number"
            },
            {
                id:9,
                val:"cust_marital_status"
            },
            {
                id:10,
                val:"cust_pps_number"
            }
        ]
    },
    {
        id:"Application",
        attr:[
            {
                id:11,
                val:"Application_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:12,
                val:"vehicle_id"
            },
            {
                id:13,
                val:"application_status"
            },
            {
                id:14,
                val:"coverage"
            }
        ]
    },
    {
        id:"Quote",
        attr:[
            {
                id:11,
                val:"Quote_id"
            },
            {
                id:11,
                val:"Application_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:16,
                val:"issue_date"
            },
            {
                id:17,
                val:"valid_from_date"
            },
            {
                id:14,
                val:"valid_till_date"
            },
            {
                id:18,
                val: "description"
            },
            {
                id:19,
                val: "product_id"
            },
            {
                id:20,
                val: "coverage_level"
            }
        ]
    },
    {
        id:"Insurance Policy",
        attr:[
            {
                id:21,
                val:"Agreement_id"
            },
            {
                id:11,
                val:"Application_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:22,
                val:"department_name"
            },
            {
                id:23,
                val:"policy_number"
            },
            {
                id:24,
                val:"start_date"
            },
            {
                id:25,
                val:"expiry_date"
            },
            {
                id:26,
                val:"term_condition_description"
            }
        ]
    },
    {
        id:"Premium Payment",
        attr:[
            {
                id:27,
                val:"Premium_payment_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:23,
                val:"policy_number"
            },
            {
                id:28,
                val:"Premium_payment_schedule"
            },
            {
                id:29,
                val:"Premium_payment_amount"
            },
            {
                id:30,
                val:"receipt_id"
            }
        ]
    },
    {
        id:"Vehicle",
        attr:[
            {
                id:31,
                val:"vehicle_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:23,
                val:"policy_id"
            },
            {
                id:32,
                val:"dependent_nok_id"
            },
            {
                id:33,
                val:"vehicle_registration_number"
            },
            {
                id:34,
                val:"vehicle_value"
            },
            {
                id:35,
                val:"vehicle_type"
            },
            {
                id:36,
                val:"vehicle_size"
            },
            {
                id:37,
                val:"vehicle_number_of_seat"
            },
            {
                id:38,
                val:"vehicle_manufacturer"
            },
            {
                id:39,
                val:"vehicle_engine_number"
            },
            {
                id:40,
                val:"vehicle_chasis_number"
            },
            {
                id:41,
                val:"vehicle_number"
            },
            {
                id:42,
                val:"vehicle_model_number"
            }
            
        ]
    },
    {
        id:"Claim",
        attr:[
            {
                id:43,
                val:"claim_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:21,
                val:"agreement_id"
            },
            {
                id:44,
                val:"claim_amount"
            },
            {
                id:45,
                val:"incident_id"
            },
            {
                id:46,
                val:"damage_type"
            },
            {
                id:47,
                val:"date_of_claim"
            },
            {
                id:48,
                val:"claim_status"
            }
            
        ]
    },
    {
        id:"Claim Settlement",
        attr:[
            {
                id:49,
                val:"claim_settlement_id"
            },
            {
                id:43,
                val:"claim_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:31,
                val:"vehicle_id"
            },
            {
                id:50,
                val:"date_settled"
            },
            {
                id:51,
                val:"amount_paid"
            },
            {
                id:52,
                val:"coverage_id"
            }
        ]
    },
    {
        id:"Staff",
        attr:[
            {
                id:53,
                val:"staff_id"
            },
            {
                id:54,
                val:"company_name"
            },
            {
                id:55,
                val:"staff_fname"
            },
            {
                id:56,
                val:"staff_lname"
            },
            {
                id:57,
                val:"staff_address"
            },
            {
                id:58,
                val:"staff_contact"
            },
            {
                id:59,
                val:"staff_gender"
            },
            {
                id:60,
                val:"staff_marital_status"
            },
            {
                id:61,
                val:"staff_nationality"
            },
            {
                id:62,
                val:"staff_qualification"
            },
            {
                id:63,
                val:"staff_allowance"
            },
            {
                id:64,
                val:"staff_pps_number"
            }
        ]
    },
    {
        id:"Department",
        attr:[
            {
                id:22,
                val:"department_name"
            },
            {
                id:54,
                val:"company_name"
            },
            {
                id:65,
                val:"office"
            },
            {
                id:66,
                val:"contact_information"
            },
            {
                id:67,
                val:"department_staff"
            },
            {
                id:68,
                val:"department_leader"
            }
        ]
    },
    {
        id:"Office",
        attr:[
            {
                id:69,
                val:"office_name"
            },
            {
                id:22,
                val:"department_name"
            },
            {
                id:54,
                val:"company_name"
            },
            {
                id:70,
                val:"office_leader"
            },
            {
                id:66,
                val:"contact_information"
            },
            {
                id:71,
                val:"address"
            },
            {
                id:72,
                val:"admin_cost"
            },
            {
                id:73,
                val:"staff"
            }
        ]
    },
    {
        id:"Membership",
        attr:[
            {
                id:74,
                val:"membership_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:75,
                val:"membership_type"
            },
            {
                id:76,
                val:"organisation_contact"
            }
        ]
    },
    {
        id:"Vehicle Service",
        attr:[
            {
                id:77,
                val:"vehicle_service"
            },
            {
                id:12,
                val:"vehicle_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:22,
                val:"department_name"
            },
            {
                id:78,
                val:"vehicle_service_address"
            },
            {
                id:79,
                val:"vehicle_service_contact"
            },
            {
                id:80,
                val:"vehicle_service_incharge"
            },
            {
                id:81,
                val:"vehicle_service_type"
            }
        ]
    },
    {
        id:"Nok",
        attr:[
            {
                id:110,
                val:"nok_id"
            },
            {
                id:21,
                val:"agreement_id"
            },
            {
                id:11,
                val:"application_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:82,
                val:"nok_name"
            },
            {
                id:83,
                val:"nok_address"
            },
            {
                id:84,
                val:"nok_phone_number"
            },
            {
                id:85,
                val:"nok_marital_status"
            },
            {
                id:86,
                val:"nok_gender"
            }
        ]
    },
    {
        id:"Insurance Company",
        attr:[
            {
                id:54,
                val:"company_name"
            },
            {
                id:87,
                val:"company_address"
            },
            {
                id:88,
                val:"company_contact_number"
            },
            {
                id:89,
                val:"company_fax"
            },
            {
                id:90,
                val:"company_email"
            },
            {
                id:91,
                val:"company_website"
            },
            {
                id:92,
                val:"company_location"
            },
            {
                id:93,
                val:"company_department_name"
            },
            {
                id:94,
                val:"company_office_name"
            }
        ]
    },
    {
        id:"Policy Renewable",
        attr:[
            {
                id:95,
                val:"policy_renewable_id"
            },
            {
                id:21,
                val:"agreement_id"
            },
            {
                id:11,
                val:"application_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:96,
                val:"date_of_renewal"
            },
            {
                id:97,
                val:"type_of_renewal"
            }
        ]
    },
    {
        id:"Incident",
        attr:[
            {
                id:98,
                val:"incident_id"
            },
            {
                id:99,
                val:"incident_type"
            },
            {
                id:100,
                val:"incident_date"
            },
            {
                id:18,
                val:"description"
            }
        ]
    },
    {
        id:"Incident Report",
        attr:[
            {
                id:101,
                val:"incident_report_id"
            },
            {
                id:45,
                val:"incident_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:102,
                val:"incident_inspector"
            },
            {
                id:103,
                val:"incident_cost"
            },
            {
                id:104,
                val:"incident_type"
            },
            {
                id:105,
                val:"incident_report_description"
            }
            
        ]
    },
    {
        id:"Coverage",
        attr:[
            {
                id:52,
                val:"coverage_id"
            },
            {
                id:54,
                val:"company_name"
            },
            {
                id:118,
                val:"coverage_amount"
            },
            {
                id:106,
                val:"coverage_type"
            },
            {
                id:107,
                val:"coverage_level"
            },
            {
                id:19,
                val:"product_id"
            },
            {
                id:108,
                val:"coverage_description"
            },
            {
                id:109,
                val:"coverage_terms"
            }
            
        ]
    },
    {
        id:"Product",
        attr:[
            {
                id:111,
                val:"product_number"
            },
            {
                id:54,
                val:"company_name"
            },
            {
                id:112,
                val:"product_price"
            },
            {
                id:113,
                val:"product_type"
            }
        ]
    },
    {
        id:"Receipt",
        attr:[
            {
                id:114,
                val:"receipt_id"
            },
            {
                id:27,
                val:"premium_payment_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:115,
                val:"cost"
            },
            {
                id:116,
                val:"time"
            }
        ]
    },
    {
        id:"Insurance Policy Coverage",
        attr:[
            {
                id:21,
                val:"agreement_id"
            },
            {
                id:52,
                val:"coverage_id"
            }
        ]
    }
]

export default tables;