const attributes = [
    {
        id:"cust_id",
        type:"text",
        attr_id:0,
        max_length:20,
        min_length:0,
        placeholder:"Customer Id",
        pattern:""
    },
    {
        id:"cust_fname",
        type:"text",
        attr_id:1,
        max_length:20,
        min_length:0,
        placeholder:"First Name",
        pattern:""
    },
    {
        id:"cust_lname",
        type:"text",
        attr_id:2,
        max_length:20,
        min_length:0,
        placeholder:"Last Name",
        pattern:""
    },{
        id:"cust_DOB",
        type:"text",
        attr_id:3,
        max_length:20,
        min_length:0,
        placeholder:"Date of Birth",
        pattern:""
    },{
        id:"cust_gender",
        type:"text",
        attr_id:4,
        max_length:20,
        min_length:0,
        placeholder:"Gender",
        pattern:""
    },{
        id:"cust_address",
        type:"text",
        attr_id:5,
        max_length:20,
        min_length:0,
        placeholder:"Address",
        pattern:""
    },{
        id:"cust_mob_number",
        type:"text",
        attr_id:6,
        max_length:13,
        min_length:10,
        placeholder:"Mobile No.",
        pattern:""
    },{
        id:"cust_email",
        type:"text",
        attr_id:7,
        max_length:20,
        min_length:0,
        placeholder:"Email",
        pattern:'\S+.*'
    },{
        id:"cust_passport_number",
        type:"text",
        attr_id:8,
        max_length:20,
        min_length:0,
        placeholder:"Passport No.",
        pattern:""
    },{
        id:"cust_marital_status",
        type:"text",
        attr_id:9,
        max_length:20,
        min_length:0,
        placeholder:"Marital Status",
        pattern:""
    },{
        id:"cust_pps_number",
        type:"text",
        attr_id:10,
        max_length:20,
        min_length:0,
        placeholder:"PPS No.",
        pattern:""
    },{
        id:"Application_id",
        type:"text",
        attr_id:11,
        max_length:20,
        min_length:0,
        placeholder:"Application No.",
        pattern:""
    },{
        id:"vehicle_id",
        type:"text",
        attr_id:12,
        max_length:20,
        min_length:0,
        placeholder:"Vehicle_id",
        pattern:""
    },{
        id:"application_status",
        type:"text",
        attr_id:13,
        max_length:20,
        min_length:0,
        placeholder:"Application Status",
        pattern:""
    },{
        id:"coverage",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Coverage",
        pattern:""
    },{
        id:"quote_id",
        type:"text",
        attr_id:15,
        max_length:20,
        min_length:0,
        placeholder:"Quoet ID",
        pattern:""
    },{
        id:"issue_date",
        type:"text",
        attr_id:16,
        max_length:20,
        min_length:0,
        placeholder:"Issue Date",
        pattern:""
    },{
        id:"valid_from_date",
        type:"text",
        attr_id:17,
        max_length:20,
        min_length:0,
        placeholder:"Valid from date",
        pattern:""
    },{
        id:"Description",
        type:"text",
        attr_id:18,
        max_length:200,
        min_length:0,
        placeholder:"Description",
        pattern:""
    },{
        id:"product_id",
        type:"text",
        attr_id:19,
        max_length:20,
        min_length:0,
        placeholder:"Product ID",
        pattern:""
    },{
        id:"coverage_level",
        type:"text",
        attr_id:20,
        max_length:20,
        min_length:0,
        placeholder:"Coverage Level",
        pattern:""
    },{
        id:"agreement_id",
        type:"text",
        attr_id:21,
        max_length:20,
        min_length:0,
        placeholder:"Agreement ID",
        pattern:""
    },{
        id:"department_name",
        type:"text",
        attr_id:22,
        max_length:20,
        min_length:0,
        placeholder:"Department Name",
        pattern:""
    },{
        id:"policy_no",
        type:"text",
        attr_id:23,
        max_length:20,
        min_length:0,
        placeholder:"Policy No.",
        pattern:""
    },{
        id:"start_date",
        type:"text",
        attr_id:24,
        max_length:20,
        min_length:0,
        placeholder:"Start Date",
        pattern:""
    },{
        id:"expiry_date",
        type:"text",
        attr_id:25,
        max_length:20,
        min_length:0,
        placeholder:"Expiry Date",
        pattern:""
    },{
        id:"terms_condition_description",
        type:"text",
        attr_id:26,
        max_length:200,
        min_length:0,
        placeholder:"Terms Condition Description",
        pattern:""
    },{
        id:"premium_payment_id",
        type:"text",
        attr_id:27,
        max_length:20,
        min_length:0,
        placeholder:"Premium Payment ID",
        pattern:""
    },{
        id:"premium_payment_schedule",
        type:"text",
        attr_id:28,
        max_length:20,
        min_length:0,
        placeholder:"Premium Payment Schedule",
        pattern:""
    },{
        id:"premium_payment_amount",
        type:"text",
        attr_id:29,
        max_length:20,
        min_length:0,
        placeholder:"Premium Payment Amount",
        pattern:""
    },{
        id:"receip_id",
        type:"text",
        attr_id:30,
        max_length:20,
        min_length:0,
        placeholder:"Receipt ID",
        pattern:""
    },{
        id:"vehicle_id",
        type:"text",
        attr_id:31,
        max_length:20,
        min_length:0,
        placeholder:"Vehicle ID",
        pattern:""
    },{
        id:"dependent_nok_id",
        type:"text",
        attr_id:32,
        max_length:20,
        min_length:0,
        placeholder:"Dependent NOK ID",
        pattern:""
    },{
        id:"Vehicle_Registration_No",
        type:"text",
        attr_id:33,
        max_length:20,
        min_length:0,
        placeholder:"Vehicle Registration No",
        pattern:""
    },{
        id:"Vehicle_Value",
        type:"text",
        attr_id:34,
        max_length:20,
        min_length:0,
        placeholder:"Vehicle Value",
        pattern:""
    },{
        id:"Vehicle_Type",
        type:"text",
        attr_id:35,
        max_length:20,
        min_length:0,
        placeholder:"Vehicle Type",
        pattern:""
    },{
        id:"Vehicle_Size",
        type:"text",
        attr_id:36,
        max_length:20,
        min_length:0,
        placeholder:"Vehicle Size",
        pattern:""
    },{
        id:"vehicle_number_of_seat",
        type:"text",
        attr_id:37,
        max_length:20,
        min_length:0,
        placeholder:"Vehicle Number of Seat",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:38,
        max_length:20,
        min_length:0,
        placeholder:"Vehicle Manufacturer",
        pattern:""
    },{
        id:"vehicle_engine_number",
        type:"text",
        attr_id:39,
        max_length:20,
        min_length:0,
        placeholder:"Vehicle Engine No",
        pattern:""
    },{
        id:"vehicle_chasis_number",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Vehicle Chasis No",
        pattern:""
    },{
        id:"vehicle_no",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Vehicle No",
        pattern:""
    },{
        id:"vehicle_model_no",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Vehicle Model No",
        pattern:""
    },{
        id:"claim_id",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Claim ID",
        pattern:""
    },{
        id:"claim_amount",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Claim Amount",
        pattern:""
    },{
        id:"incident_id",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Incident ID",
        pattern:""
    },{
        id:"damage_type",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Damage Type",
        pattern:""
    },{
        id:"date_of_claim",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Date of claim",
        pattern:""
    },{
        id:"claim_status",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Claim Status",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    },{
        id:"vehicle_manufacturer",
        type:"text",
        attr_id:14,
        max_length:20,
        min_length:0,
        placeholder:"Manufacturer",
        pattern:""
    }
]

export default attributes;
