const tables = [
    {
        id:"Customer",
        attr:[
            {
                id:0,
                val:"cust_id"
            },
            {
                id:1,
                val:"cust_fname"
            },
            {
                id:2,
                val:"cust_lname"
            },
            {
                id:3,
                val:"cust_DOB"
            },
            {
                id:4,
                val:"cust_gender"
            },
            {
                id:5,
                val:"cust_address"
            },
            {
                id:6,
                val:"cust_mob_number"
            },
            {
                id:7,
                val:"cust_email"
            },
            {
                id:8,
                val:"cust_passport_number"
            },
            {
                id:9,
                val:"cust_marital_status"
            },
            {
                id:10,
                val:"cust_pps_number"
            }
        ]
    },
    {
        id:"Application",
        attr:[
            {
                id:11,
                val:"Application_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:12,
                val:"vehicle_id"
            },
            {
                id:13,
                val:"application_status"
            },
            {
                id:14,
                val:"coverage"
            }
        ]
    }
]

export default tables;