const tables = [
    {
        id:"Customer",
        attr:[
            {
                id:0,
                val:"cust_id"
            },
            {
                id:1,
                val:"cust_fname"
            },
            {
                id:2,
                val:"cust_lname"
            },
            {
                id:3,
                val:"cust_DOB"
            },
            {
                id:4,
                val:"cust_gender"
            },
            {
                id:5,
                val:"cust_address"
            },
            {
                id:6,
                val:"cust_mob_number"
            },
            {
                id:7,
                val:"cust_email"
            },
            {
                id:8,
                val:"cust_passport_number"
            },
            {
                id:9,
                val:"cust_marital_status"
            },
            {
                id:10,
                val:"cust_pps_number"
            }
        ]
    },
    {
        id:"Application",
        attr:[
            {
                id:11,
                val:"Application_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:12,
                val:"vehicle_id"
            },
            {
                id:13,
                val:"application_status"
            },
            {
                id:14,
                val:"coverage"
            }
        ]
    },
    {
        id:"Quote",
        attr:[
            {
                id:11,
                val:"Quote_id"
            },
            {
                id:11,
                val:"Application_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:16,
                val:"issue_date"
            },
            {
                id:17,
                val:"valid_from_date"
            },
            {
                id:14,
                val:"valid_till_date"
            },
            {
                id:18,
                val: "description"
            },
            {
                id:19,
                val: "product_id"
            },
            {
                id:20,
                val: "coverage_level"
            }
        ]
    },
    {
        id:"Insurance_policy",
        attr:[
            {
                id:21,
                val:"Agreement_id"
            },
            {
                id:11,
                val:"Application_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:22,
                val:"department_name"
            },
            {
                id:23,
                val:"policy_number"
            },
            {
                id:24,
                val:"start_date"
            },
            {
                id:25,
                val:"expiry_date"
            },
            {
                id:26,
                val:"term_condition_description"
            }
        ]
    },
    {
        id:"Premium_payment",
        attr:[
            {
                id:27,
                val:"Premium_payment_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:23,
                val:"policy_number"
            },
            {
                id:28,
                val:"Premium_payment_schedule"
            },
            {
                id:29,
                val:"Premium_payment_amount"
            },
            {
                id:30,
                val:"receipt_id"
            }
        ]
    },
    {
        id:"Vehicle",
        attr:[
            {
                id:11,
                val:"vehicle_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:12,
                val:"policy_id"
            },
            {
                id:13,
                val:"DEPENDENT_NOK_ID"
            },
            {
                id:14,
                val:"VEHICLE_REGISTRATION_NUMBER"
            },
            {
                id:14,
                val:"VEHICLE_VALUE"
            },
            {
                id:14,
                val:"VEHICLE_TYPE"
            },
            {
                id:14,
                val:"VEHICLE_SIZE"
            },
            {
                id:14,
                val:"VEHICLE_NUMBER_OF_SEAT"
            },
            {
                id:14,
                val:"VEHICLE_MANUFACTURER"
            },
            {
                id:14,
                val:"VEHICLE_CHASIS_NUMBER"
            },
            {
                id:14,
                val:"VEHICLE_NUMBER"
            },
            {
                id:14,
                val:"VEHICLE_MODEL_NUMBER"
            }
            
        ]
    },
    {
        id:"Claim",
        attr:[
            {
                id:11,
                val:"CLAIM_ID"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:12,
                val:"AGREEMENT_ID"
            },
            {
                id:13,
                val:"CLAIM_AMOUNT"
            },
            {
                id:14,
                val:"INCIDENT_ID"
            },
            {
                id:14,
                val:"DAMAGE_TYPE"
            },
            {
                id:14,
                val:"DATE_OF_CLAIM"
            },
            {
                id:14,
                val:"CLAIM_STATUS"
            }
            
        ]
    },
    {
        id:"CLAIM_SETTLEMENT",
        attr:[
            {
                id:11,
                val:"CLAIM_SETTLEMENT_ID"
            },
            {
                id:0,
                val:"CLAIM_ID"
            },
            {
                id:12,
                val:"CUST_ID"
            },
            {
                id:13,
                val:"VEHICLE_ID"
            },
            {
                id:14,
                val:"DATE_SETTLED"
            },
            {
                id:14,
                val:"AMOUNT_PAID"
            },
            {
                id:14,
                val:"COVERAGE_ID"
            }
        ]
    },
    {
        id:"STAFF",
        attr:[
            {
                id:11,
                val:"STAFF"
            },
            {
                id:0,
                val:"COMPANY_NAME"
            },
            {
                id:12,
                val:"STAFF_FNAME"
            },
            {
                id:13,
                val:"STAFF_LNAME"
            },
            {
                id:14,
                val:"STAFF_ADDRESS"
            },
            {
                id:14,
                val:"STAFF_CONTACT"
            },
            {
                id:14,
                val:"STAFF_GENDER"
            },
            {
                id:14,
                val:"STAFF_MARITAL_STATUS"
            },
            {
                id:14,
                val:"STAFF_NATIONALITY"
            },
            {
                id:14,
                val:"STAFF_QUALIFICATION"
            },
            {
                id:14,
                val:"STAFF_ALLOWANCE"
            },
            {
                id:14,
                val:"STAFF_PPS_NUMBER"
            }
        ]
    },
    {
        id:"DEPARTMENT",
        attr:[
            {
                id:11,
                val:"DEPARTMENT_NAME"
            },
            {
                id:0,
                val:"COMPANY_NAME"
            },
            {
                id:12,
                val:"OFFICE"
            },
            {
                id:13,
                val:"CONTACT_INFORMATION"
            },
            {
                id:14,
                val:"DEPARTMENT_STAFF"
            },
            {
                id:14,
                val:"DEPARTMENT_LEADER"
            }
        ]
    },
    {
        id:"OFFICE",
        attr:[
            {
                id:11,
                val:"OFFICE_NAME"
            },
            {
                id:0,
                val:"DEPARTMENT_NAME"
            },
            {
                id:12,
                val:"COMPANY_NAME"
            },
            {
                id:13,
                val:"OFFICE_LEADER"
            },
            {
                id:14,
                val:"CONTACT_INFORMATION"
            },
            {
                id:14,
                val:"ADDRESS"
            },
            {
                id:14,
                val:"ADMIN_COST"
            },
            {
                id:14,
                val:"STAFF"
            }
        ]
    },
    {
        id:"MEMBERSHIP",
        attr:[
            {
                id:11,
                val:"MEMBERSHIP_ID"
            },
            {
                id:0,
                val:"CUST_ID"
            },
            {
                id:12,
                val:"MEMBERSHIP_TYPE"
            },
            {
                id:13,
                val:"ORGANISATION_CONTACT"
            }
        ]
    },
    {
        id:"VEHICLE_SERVICE",
        attr:[
            {
                id:11,
                val:"VEHICLE_SERVICE"
            },
            {
                id:0,
                val:"VEHICLE_ID"
            },
            {
                id:12,
                val:"CUST_ID"
            },
            {
                id:13,
                val:"DEPARTMENT_NAME"
            },
            {
                id:11,
                val:"VEHICLE_SERVICE_ADDRESS"
            },
            {
                id:0,
                val:"VEHICLE_SERVICE_CONTACT"
            },
            {
                id:12,
                val:"VEHICLE_SERVICE_INCHARGE"
            },
            {
                id:13,
                val:"VEHICLE_SERVICE_TYPE"
            }
        ]
    },
    {
        id:"NOK",
        attr:[
            {
                id:11,
                val:"NOK_ID"
            },
            {
                id:0,
                val:"AGREEMENT_ID"
            },
            {
                id:12,
                val:"APPLICATION_ID"
            },
            {
                id:13,
                val:"CUST_ID"
            },
            {
                id:11,
                val:"NOK_NAME"
            },
            {
                id:0,
                val:"NOK_ADDRESS"
            },
            {
                id:12,
                val:"NOK_PHONE_NUMBER"
            },
            {
                id:13,
                val:"NOK_MARITAL_STATUS"
            },
            {
                id:13,
                val:"NOK_GENDER"
            }
        ]
    },
    {
        id:"INSURANCE_COMPANY",
        attr:[
            {
                id:11,
                val:"COMPANY_NAME"
            },
            {
                id:0,
                val:"COMPANY_ADDRESS"
            },
            {
                id:12,
                val:"COMPANY_CONTACT_NUMBER"
            },
            {
                id:13,
                val:"COMPANY_FAX"
            },
            {
                id:11,
                val:"COMPANY_EMAIL"
            },
            {
                id:0,
                val:"COMPANY_WEBSITE"
            },
            {
                id:12,
                val:"COMPANY_LOCATION"
            },
            {
                id:13,
                val:"COMPANY_DEPARTMENT_NAME"
            },
            {
                id:13,
                val:"COMPANY_OFFICE_NAME"
            }
        ]
    },
    {
        id:"POLICY_RENEWABLE",
        attr:[
            {
                id:11,
                val:"POLICY_RENEWABLE_ID"
            },
            {
                id:0,
                val:"AGREEMENT_ID"
            },
            {
                id:0,
                val:"APPLICATION_ID"
            },
            {
                id:12,
                val:"CUST_ID"
            },
            {
                id:13,
                val:"DATE_OF_RENEWAL"
            },
            {
                id:11,
                val:"TYPE_OF_RENEWAL"
            }
        ]
    },
    {
        id:"INCIDENT",
        attr:[
            {
                id:11,
                val:"INCIDENT_ID"
            },
            {
                id:0,
                val:"INCIDENT_TYPE"
            },
            {
                id:0,
                val:"INCIDENT_DATE"
            },
            {
                id:12,
                val:"DESCRIPTION"
            }
        ]
    },
    {
        id:"INCIDENT_REPORT",
        attr:[
            {
                id:11,
                val:"INCIDENT_REPORT_ID"
            },
            {
                id:0,
                val:"INCIDENT_ID"
            },
            {
                id:0,
                val:"CUST_ID"
            },
            {
                id:12,
                val:"INCIDENT_INSPECTOR"
            },
            {
                id:12,
                val:"INCIDENT_COST"
            },
            {
                id:12,
                val:"INCIDENT_TYPE"
            },
            {
                id:12,
                val:"INCIDENT_REPORT_DESCRIPTION"
            }
            
        ]
    },
    {
        id:"COVERAGE",
        attr:[
            {
                id:11,
                val:"COVERAGE_ID"
            },
            {
                id:0,
                val:"COMPANY_NAME"
            },
            {
                id:0,
                val:"COVERAGE_AMOUNT"
            },
            {
                id:12,
                val:"COVERAGE_TYPE"
            },
            {
                id:12,
                val:"COVERAGE_LEVEL"
            },
            {
                id:12,
                val:"PRODUCT_ID"
            },
            {
                id:12,
                val:"COVERAGE_DESCRIPTION"
            },
            {
                id:12,
                val:"COVERAGE_TERMS"
            }
            
        ]
    },
    {
        id:"PRODUCT",
        attr:[
            {
                id:11,
                val:"PRODUCT_NUMBER"
            },
            {
                id:0,
                val:"COMPANY_NAME"
            },
            {
                id:0,
                val:"PRODUCT_PRICE"
            },
            {
                id:12,
                val:"PRODUCT_TYPE"
            }
        ]
    },
    {
        id:"RECEIPT",
        attr:[
            {
                id:11,
                val:"RECEIPT_ID"
            },
            {
                id:0,
                val:"PREMIUM_PAYMENT_ID"
            },
            {
                id:0,
                val:"CUST_ID"
            },
            {
                id:12,
                val:"COST"
            },
            {
                id:12,
                val:"TIME"
            }
        ]
    },
    {
        id:"INSURANCE_POLICY_COVERAGE",
        attr:[
            {
                id:11,
                val:"AGREEMENT_ID"
            },
            {
                id:0,
                val:"AGREEMENT_ID"
            }
        ]
    }
]

export default tables;
