const tables = [
    {
        id:"Customer",
        attr:[
            {
                id:0,
                val:"cust_id"
            },
            {
                id:1,
                val:"cust_fname"
            },
            {
                id:2,
                val:"cust_lname"
            },
            {
                id:3,
                val:"cust_DOB"
            },
            {
                id:4,
                val:"cust_gender"
            },
            {
                id:5,
                val:"cust_address"
            },
            {
                id:6,
                val:"cust_mob_number"
            },
            {
                id:7,
                val:"cust_email"
            },
            {
                id:8,
                val:"cust_passport_number"
            },
            {
                id:9,
                val:"cust_marital_status"
            },
            {
                id:10,
                val:"cust_pps_number"
            }
        ]
    },
    {
        id:"Application",
        attr:[
            {
                id:11,
                val:"Application_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:12,
                val:"vehicle_id"
            },
            {
                id:13,
                val:"application_status"
            },
            {
                id:14,
                val:"coverage"
            }
        ]
    },
    {
        id:"Quote",
        attr:[
            {
                id:11,
                val:"Quote_id"
            },
            {
                id:11,
                val:"Application_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:16,
                val:"issue_date"
            },
            {
                id:17,
                val:"valid_from_date"
            },
            {
                id:14,
                val:"valid_till_date"
            },
            {
                id:18,
                val: "description"
            },
            {
                id:19,
                val: "product_id"
            },
            {
                id:20,
                val: "coverage_level"
            }
        ]
    },
    {
        id:"Insurance_policy",
        attr:[
            {
                id:21,
                val:"Agreement_id"
            },
            {
                id:11,
                val:"Application_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:22,
                val:"department_name"
            },
            {
                id:23,
                val:"policy_number"
            },
            {
                id:24,
                val:"start_date"
            },
            {
                id:25,
                val:"expiry_date"
            },
            {
                id:26,
                val:"term_condition_description"
            }
        ]
    },
    {
        id:"Premium_payment",
        attr:[
            {
                id:27,
                val:"Premium_payment_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:23,
                val:"policy_number"
            },
            {
                id:28,
                val:"Premium_payment_schedule"
            },
            {
                id:29,
                val:"Premium_payment_amount"
            },
            {
                id:30,
                val:"receipt_id"
            }
        ]
    },
    {
        id:"Vehicle",
        attr:[
            {
                id:31,
                val:"vehicle_id"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:23,
                val:"policy_id"
            },
            {
                id:32,
                val:"DEPENDENT_NOK_ID"
            },
            {
                id:33,
                val:"VEHICLE_REGISTRATION_NUMBER"
            },
            {
                id:34,
                val:"VEHICLE_VALUE"
            },
            {
                id:35,
                val:"VEHICLE_TYPE"
            },
            {
                id:36,
                val:"VEHICLE_SIZE"
            },
            {
                id:37,
                val:"VEHICLE_NUMBER_OF_SEAT"
            },
            {
                id:38,
                val:"VEHICLE_MANUFACTURER"
            },
            {
                id:39,
                val:"VEHICLE_ENGINE_NUMBER"
            },
            {
                id:40,
                val:"VEHICLE_CHASIS_NUMBER"
            },
            {
                id:41,
                val:"VEHICLE_NUMBER"
            },
            {
                id:42,
                val:"VEHICLE_MODEL_NUMBER"
            }
            
        ]
    },
    {
        id:"Claim",
        attr:[
            {
                id:43,
                val:"CLAIM_ID"
            },
            {
                id:0,
                val:"cust_id"
            },
            {
                id:21,
                val:"AGREEMENT_ID"
            },
            {
                id:44,
                val:"CLAIM_AMOUNT"
            },
            {
                id:45,
                val:"INCIDENT_ID"
            },
            {
                id:46,
                val:"DAMAGE_TYPE"
            },
            {
                id:47,
                val:"DATE_OF_CLAIM"
            },
            {
                id:48,
                val:"CLAIM_STATUS"
            }
            
        ]
    },
    {
        id:"CLAIM_SETTLEMENT",
        attr:[
            {
                id:49,
                val:"CLAIM_SETTLEMENT_ID"
            },
            {
                id:43,
                val:"CLAIM_ID"
            },
            {
                id:0,
                val:"CUST_ID"
            },
            {
                id:31,
                val:"VEHICLE_ID"
            },
            {
                id:50,
                val:"DATE_SETTLED"
            },
            {
                id:51,
                val:"AMOUNT_PAID"
            },
            {
                id:52,
                val:"COVERAGE_ID"
            }
        ]
    },
    {
        id:"STAFF",
        attr:[
            {
                id:53,
                val:"STAFF_ID"
            },
            {
                id:54,
                val:"COMPANY_NAME"
            },
            {
                id:55,
                val:"STAFF_FNAME"
            },
            {
                id:56,
                val:"STAFF_LNAME"
            },
            {
                id:57,
                val:"STAFF_ADDRESS"
            },
            {
                id:58,
                val:"STAFF_CONTACT"
            },
            {
                id:59,
                val:"STAFF_GENDER"
            },
            {
                id:60,
                val:"STAFF_MARITAL_STATUS"
            },
            {
                id:61,
                val:"STAFF_NATIONALITY"
            },
            {
                id:62,
                val:"STAFF_QUALIFICATION"
            },
            {
                id:63,
                val:"STAFF_ALLOWANCE"
            },
            {
                id:64,
                val:"STAFF_PPS_NUMBER"
            }
        ]
    },
    {
        id:"DEPARTMENT",
        attr:[
            {
                id:22,
                val:"DEPARTMENT_NAME"
            },
            {
                id:54,
                val:"COMPANY_NAME"
            },
            {
                id:65,
                val:"OFFICE"
            },
            {
                id:66,
                val:"CONTACT_INFORMATION"
            },
            {
                id:67,
                val:"DEPARTMENT_STAFF"
            },
            {
                id:68,
                val:"DEPARTMENT_LEADER"
            }
        ]
    },
    {
        id:"OFFICE",
        attr:[
            {
                id:69,
                val:"OFFICE_NAME"
            },
            {
                id:22,
                val:"DEPARTMENT_NAME"
            },
            {
                id:54,
                val:"COMPANY_NAME"
            },
            {
                id:70,
                val:"OFFICE_LEADER"
            },
            {
                id:66,
                val:"CONTACT_INFORMATION"
            },
            {
                id:71,
                val:"ADDRESS"
            },
            {
                id:72,
                val:"ADMIN_COST"
            },
            {
                id:73,
                val:"STAFF"
            }
        ]
    },
    {
        id:"MEMBERSHIP",
        attr:[
            {
                id:74,
                val:"MEMBERSHIP_ID"
            },
            {
                id:0,
                val:"CUST_ID"
            },
            {
                id:75,
                val:"MEMBERSHIP_TYPE"
            },
            {
                id:76,
                val:"ORGANISATION_CONTACT"
            }
        ]
    },
    {
        id:"VEHICLE_SERVICE",
        attr:[
            {
                id:77,
                val:"VEHICLE_SERVICE"
            },
            {
                id:12,
                val:"VEHICLE_ID"
            },
            {
                id:0,
                val:"CUST_ID"
            },
            {
                id:22,
                val:"DEPARTMENT_NAME"
            },
            {
                id:78,
                val:"VEHICLE_SERVICE_ADDRESS"
            },
            {
                id:79,
                val:"VEHICLE_SERVICE_CONTACT"
            },
            {
                id:80,
                val:"VEHICLE_SERVICE_INCHARGE"
            },
            {
                id:81,
                val:"VEHICLE_SERVICE_TYPE"
            }
        ]
    },
    {
        id:"NOK",
        attr:[
            {
                id:'*',
                val:"NOK_ID"
            },
            {
                id:21,
                val:"AGREEMENT_ID"
            },
            {
                id:11,
                val:"APPLICATION_ID"
            },
            {
                id:0,
                val:"CUST_ID"
            },
            {
                id:82,
                val:"NOK_NAME"
            },
            {
                id:83,
                val:"NOK_ADDRESS"
            },
            {
                id:84,
                val:"NOK_PHONE_NUMBER"
            },
            {
                id:85,
                val:"NOK_MARITAL_STATUS"
            },
            {
                id:86,
                val:"NOK_GENDER"
            }
        ]
    },
    {
        id:"INSURANCE_COMPANY",
        attr:[
            {
                id:54,
                val:"COMPANY_NAME"
            },
            {
                id:87,
                val:"COMPANY_ADDRESS"
            },
            {
                id:88,
                val:"COMPANY_CONTACT_NUMBER"
            },
            {
                id:89,
                val:"COMPANY_FAX"
            },
            {
                id:90,
                val:"COMPANY_EMAIL"
            },
            {
                id:91,
                val:"COMPANY_WEBSITE"
            },
            {
                id:92,
                val:"COMPANY_LOCATION"
            },
            {
                id:93,
                val:"COMPANY_DEPARTMENT_NAME"
            },
            {
                id:94,
                val:"COMPANY_OFFICE_NAME"
            }
        ]
    },
    {
        id:"POLICY_RENEWABLE",
        attr:[
            {
                id:95,
                val:"POLICY_RENEWABLE_ID"
            },
            {
                id:21,
                val:"AGREEMENT_ID"
            },
            {
                id:11,
                val:"APPLICATION_ID"
            },
            {
                id:0,
                val:"CUST_ID"
            },
            {
                id:96,
                val:"DATE_OF_RENEWAL"
            },
            {
                id:97,
                val:"TYPE_OF_RENEWAL"
            }
        ]
    },
    {
        id:"INCIDENT",
        attr:[
            {
                id:98,
                val:"INCIDENT_ID"
            },
            {
                id:99,
                val:"INCIDENT_TYPE"
            },
            {
                id:100,
                val:"INCIDENT_DATE"
            },
            {
                id:18,
                val:"DESCRIPTION"
            }
        ]
    },
    {
        id:"INCIDENT_REPORT",
        attr:[
            {
                id:101,
                val:"INCIDENT_REPORT_ID"
            },
            {
                id:45,
                val:"INCIDENT_ID"
            },
            {
                id:0,
                val:"CUST_ID"
            },
            {
                id:102,
                val:"INCIDENT_INSPECTOR"
            },
            {
                id:103,
                val:"INCIDENT_COST"
            },
            {
                id:104,
                val:"INCIDENT_TYPE"
            },
            {
                id:105,
                val:"INCIDENT_REPORT_DESCRIPTION"
            }
            
        ]
    },
    {
        id:"COVERAGE",
        attr:[
            {
                id:52,
                val:"COVERAGE_ID"
            },
            {
                id:54,
                val:"COMPANY_NAME"
            },
            {
                id:118,
                val:"COVERAGE_AMOUNT"
            },
            {
                id:106,
                val:"COVERAGE_TYPE"
            },
            {
                id:107,
                val:"COVERAGE_LEVEL"
            },
            {
                id:19,
                val:"PRODUCT_ID"
            },
            {
                id:108,
                val:"COVERAGE_DESCRIPTION"
            },
            {
                id:109,
                val:"COVERAGE_TERMS"
            }
            
        ]
    },
    {
        id:"PRODUCT",
        attr:[
            {
                id:111,
                val:"PRODUCT_NUMBER"
            },
            {
                id:54,
                val:"COMPANY_NAME"
            },
            {
                id:112,
                val:"PRODUCT_PRICE"
            },
            {
                id:113,
                val:"PRODUCT_TYPE"
            }
        ]
    },
    {
        id:"RECEIPT",
        attr:[
            {
                id:114,
                val:"RECEIPT_ID"
            },
            {
                id:27,
                val:"PREMIUM_PAYMENT_ID"
            },
            {
                id:0,
                val:"CUST_ID"
            },
            {
                id:115,
                val:"COST"
            },
            {
                id:116,
                val:"TIME"
            }
        ]
    },
    {
        id:"INSURANCE_POLICY_COVERAGE",
        attr:[
            {
                id:21,
                val:"AGREEMENT_ID"
            },
            {
                id:52,
                val:"COVERAGE_ID"
            }
        ]
    }
]

export default tables;
